name: Rakshit's Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"  # Updates daily
  workflow_dispatch:      # Lets you manually run it
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rakshitsinghhh  # Your username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
